--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/users/bswang/PCIe_BlockDMA/tb/ip/safifo512x128.vhd
 -- Date	:	2022 11 30
 -- TD version	:	5.7.64266
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY safifo512x128 IS
PORT (
	di	: IN STD_LOGIC_VECTOR(127 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	dout	: OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(9 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(9 DOWNTO 0)
	);
END safifo512x128;

ARCHITECTURE struct OF safifo512x128 IS

	BEGIN
	inst : PH1_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 128,
			ADDR_WIDTH			=> 9,
			SHOWAHEAD			=> 1,
			IMPLEMENT			=>"20K(FAST)"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			dout	=> dout,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
