--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/users/bswang/PCIe_SGDMA_MM/tb/ip/sfifo512x32.vhd
 -- Date	:	2022 12 03
 -- TD version	:	5.7.64597
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY sfifo512x32 IS
PORT (
    wrst	: IN STD_LOGIC;
    rrst	: IN STD_LOGIC;
    di	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);

    clk	: IN STD_LOGIC;
    we	: IN STD_LOGIC;
    re	: IN STD_LOGIC;
    dout	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

    empty_flag	: OUT STD_LOGIC;
    full_flag	: OUT STD_LOGIC;
    fifo_wrpointer	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);

    fifo_rdpointer	: OUT STD_LOGIC_VECTOR(8 DOWNTO 0)

);
END sfifo512x32;

ARCHITECTURE struct OF sfifo512x32 IS

    BEGIN
        fifo_inst : PH1_LOGIC_FIFO
            GENERIC MAP (
                DATA_WIDTH	=> 32,
                ADDR_WIDTH	=> 9,
                REGMODE_R	=> "NOREG",
                FIRSTWRITE_RD	=> "DISABLE",
                ASYNC_RESET_RELEASE	=> "SYNC",
                CLKMODE	=> "SYNC",
                SSROVERCE	=> "DISABLE",
                ECC_ENCODE	=> "DISABLE",
                ECC_DECODE	=> "DISABLE"
            )
            PORT MAP (
			wrst	=> wrst,
			rrst	=> rrst,
			di	=> di,
			clkw	=> clk,
			we	=> we,
			csw	=> "111",
			clkr	=> clk,
			re	=> re,
			csr	=> "111",
			dout	=> dout,
			empty_flag	=> empty_flag,
			aempty_flag	=> OPEN,
			full_flag	=> full_flag,
			afull_flag	=> OPEN,
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			fifo_wrpointer	=> fifo_wrpointer,
			fifo_rdpointer	=> fifo_rdpointer
            );

END struct;
