../def/bdf.vh 
../def/cfg_addr_table.vh 
../def/dt_para.vh 
../bfm/dbi_master_bfm.v 
../def/ep_para_def.vh 
../ip_sim/fifo_512dw_sim.v 
../bfm/msi_int_bfm.v 
../bfm/pcie_ep_bfm.v 
../ip_sim/pcie_ep_core.v 
../bfm/pcie_rc_bfm.v 
../ip_sim/pcie_rc_core.v 
../bfm/pcie_rx_bfm.v 
../bfm/pcie_tx_bfm.v 
../def/rc_para_def.vh 
../ip_sim/rx_sfifo512x128_sim.v 
../ip_sim/showahead_sfifo512x128.v
../bfm/cfg_init.v
../bfm/ip_regrw.v
../bfm/ip_datarw.v
../bfm/tlp_access_rc.v
../ip_sim/trgt1_rx_ram128x10.v
../bfm/byps_cpl.v

../../src/sgdma_ip/src/mrd_relor.v
../../src/sgdma_ip/src/mrd_rx.v 
../../src/sgdma_ip/src/dscpr_cal.v 
../../src/sgdma_ip/src/dscpw_cal.v 
../../src/sgdma_ip/src/app_dmarw.v 
../../src/sgdma_ip/src/drv_usrrw.v 
../../src/sgdma_ip/src/excep_hndl.v 
../../src/sgdma_ip/src/irq_hndl.v 
../../src/sgdma_ip/src/mrd_arb.v 
//../../src/sgdma_ip/src/mrd_axi4mm.v 
../../src/sgdma_ip/src/mrd_axi4s0.v 
//../../src/sgdma_ip/src/mrd_axi4s1.v 
../../src/sgdma_ip/src/mrd_tlp.v 
../../src/sgdma_ip/src/mwr_arb.v 
//../../src/sgdma_ip/src/mwr_axi4mm.v 
../../src/sgdma_ip/src/mwr_axi4s0.v 
//../../src/sgdma_ip/src/mwr_axi4s1.v 
../../src/sgdma_ip/src/mwr_tlp.v 
../../src/sgdma_ip/src/pcie_cfgrw.v 
../../src/sgdma_ip/src/perf_stat.v 
../../src/sgdma_ip/src/rdscp_cal.v 
../../src/sgdma_ip/src/mrd_schd.v 
../../src/sgdma_ip/src/sgdma_ctrl.v 
../../src/sgdma_ip/src/sgdma_ip.v 
../../src/sgdma_ip/src/sgdma_regrw.v
../../src/sgdma_ip/src/wdscp_cal.v 
../../src/sgdma_ip/def/para_def.vh 
../../src/sgdma_ip/ip/ram512x64.v  
../../src/sgdma_ip/ip/ram512x128.v 
../../src/sgdma_ip/ip/safifo512x64.v  
../../src/sgdma_ip/ip/dram32x13.v 
../../src/sgdma_ip/ip/dram32x12.v 
../../src/sgdma_ip/ip/ram512x27.v 
../../src/sgdma_ip/ip_sim/sfifo512x16_sim.v 
../../src/sgdma_ip/ip_sim/sfifo512x128_sim.v
../../src/sgdma_ip/ip_sim/sfifo512x64_sim.v
../top/tb_sgdma_fsim.v

../../src/sgdma_app/src/usr_regrw.v 
../../src/sgdma_app/src/dma_regrw.v 
../../src/sgdma_app/src/cfg_regrw.v 
../../src/sgdma_app/src/sgdma_app.v 
../../src/sgdma_app/src/app_tst_ctrl.v 
../../src/sgdma_app/src/usr_c2h0r.v
../../src/sgdma_app/src/usr_h2c0w.v
../../src/sgdma_app/ip_sim/usr_regrw_bram512x32_sim.v

