--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/users/hge/work/sgdma_100/PCIe_SGDMAfor_PH1A100/sgdam_prj/src/sgdma_ip/ip/pcie_cfg_rom.vhd
 -- Date	:	2023 06 26
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY pcie_cfg_rom IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(67 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(6 DOWNTO 0);
	clka		: IN STD_LOGIC
	);
END pcie_cfg_rom;

ARCHITECTURE struct OF pcie_cfg_rom IS

	BEGIN
	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 68,
			ADDR_WIDTH_A	=> 7,
			DATA_DEPTH_A	=> 128,
			DATA_WIDTH_B	=> 68,
			ADDR_WIDTH_B	=> 7,
			DATA_DEPTH_B	=> 128,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			IMPLEMENT	=> "20K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "pcie_ep_core.dat",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> '0',
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
