// Verilog netlist created by TD v5.0.43066
// Mon Apr 11 10:29:07 2022

`timescale 1ns / 1ps
module sys_pll  // sys_pll.v(23)
  (
  refclk,
  reset,
  clk0_out,
  clk1_out,
  lock
  );

  input refclk;  // sys_pll.v(29)
  input reset;  // sys_pll.v(30)
  output clk0_out;  // sys_pll.v(32)
  output clk1_out;  // sys_pll.v(33)
  output lock;  // sys_pll.v(31)

  wire clk0_buf;  // sys_pll.v(35)

  PH1_PHY_GCLK bufg_feedback (
    .cen(2'b10),
    .clkin({open_n0,clk0_buf}),
    .drct(2'b00),
    .seln(2'b10),
    .clkout(clk0_out));  // sys_pll.v(37)
  PH1_PHY_CONFIG #(
    .DONE_PERSISTN("DISABLE"),
    .INITN_PERSISTN("DISABLE"),
    .JTAG_PERSISTN("DISABLE"),
    .PROGRAMN_PERSISTN("DISABLE"),
    .SPIX4_PERSISTN("ENABLE"))
    config_inst ();
  PH1_PHY_PLL #(
    .CLKC0_CPHASE(7),
    .CLKC0_CPHASE_DIV2(0),
    .CLKC0_DIV(8),
    .CLKC0_DIV2_ENABLE("DISABLE"),
    .CLKC0_DUTY50("ENABLE"),
    .CLKC0_DUTY_INT(4),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_FPHASE(0),
    .CLKC0_FPHASE_RSTSEL(0),
    .CLKC0_USR_RST("ENABLE"),
    .CLKC1_CPHASE(7),
    .CLKC1_CPHASE_DIV2(0),
    .CLKC1_DIV(8),
    .CLKC1_DIV2_ENABLE("DISABLE"),
    .CLKC1_DUTY50("ENABLE"),
    .CLKC1_DUTY_INT(4),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_FPHASE(0),
    .CLKC1_FPHASE_RSTSEL(0),
    .CLKC1_USR_RST("ENABLE"),
    .CLKC2_CPHASE(0),
    .CLKC2_CPHASE_DIV2(0),
    .CLKC2_DIV(1),
    .CLKC2_DIV2_ENABLE("DISABLE"),
    .CLKC2_DUTY50("ENABLE"),
    .CLKC2_DUTY_INT(1),
    .CLKC2_ENABLE("DISABLE"),
    .CLKC2_FPHASE(0),
    .CLKC2_FPHASE_RSTSEL(0),
    .CLKC3_CPHASE(0),
    .CLKC3_CPHASE_DIV2(0),
    .CLKC3_DIV(1),
    .CLKC3_DIV2_ENABLE("DISABLE"),
    .CLKC3_DUTY50("ENABLE"),
    .CLKC3_DUTY_INT(1),
    .CLKC3_ENABLE("DISABLE"),
    .CLKC3_FPHASE(0),
    .CLKC3_FPHASE_RSTSEL(0),
    .CLKC4_CPHASE(0),
    .CLKC4_CPHASE_DIV2(0),
    .CLKC4_DIV(1),
    .CLKC4_DIV2_ENABLE("DISABLE"),
    .CLKC4_DUTY50("ENABLE"),
    .CLKC4_DUTY_INT(1),
    .CLKC4_ENABLE("DISABLE"),
    .CLKC4_FPHASE(0),
    .CLKC4_FPHASE_RSTSEL(0),
    .CLKC5_CPHASE(0),
    .CLKC5_CPHASE_DIV2(0),
    .CLKC5_DIV(1),
    .CLKC5_DIV2_ENABLE("DISABLE"),
    .CLKC5_DUTY50("ENABLE"),
    .CLKC5_DUTY_INT(1),
    .CLKC5_ENABLE("DISABLE"),
    .CLKC5_FPHASE(0),
    .CLKC5_FPHASE_RSTSEL(0),
    .CLKC6_CPHASE(0),
    .CLKC6_CPHASE_DIV2(0),
    .CLKC6_DIV(1),
    .CLKC6_DIV2_ENABLE("DISABLE"),
    .CLKC6_DUTY50("ENABLE"),
    .CLKC6_DUTY_INT(1),
    .CLKC6_ENABLE("DISABLE"),
    .CLKC6_FPHASE(0),
    .CLKC6_FPHASE_RSTSEL(0),
    .CLK_MAIN_ENABLE("DISABLE"),
    .DERIVE_PLL_CLOCKS("DISABLE"),
    .DITHER_ENABLE("DISABLE"),
    .DIVOUT_MUXC0("DIV"),
    .DIVOUT_MUXC1("DIV"),
    .DIVOUT_MUXC2("DIV"),
    .DIVOUT_MUXC3("DIV"),
    .DIVOUT_MUXC4("DIV"),
    .DIVOUT_MUXC5("DIV"),
    .DIVOUT_MUXC6("DIV"),
    .DYN_CPHASE_CLKC0_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC0_DIV_EN("DISABLE"),
    .DYN_CPHASE_CLKC1_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC1_DIV_EN("DISABLE"),
    .DYN_CPHASE_CLKC2_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC2_DIV_EN("DISABLE"),
    .DYN_CPHASE_CLKC3_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC3_DIV_EN("DISABLE"),
    .DYN_CPHASE_CLKC4_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC4_DIV_EN("DISABLE"),
    .DYN_CPHASE_CLKC5_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC5_DIV_EN("DISABLE"),
    .DYN_CPHASE_CLKC6_DIV2_EN("DISABLE"),
    .DYN_CPHASE_CLKC6_DIV_EN("DISABLE"),
    .DYN_FPHASE_EN("DISABLE"),
    .DYN_PHASE_PATH_SEL("DISABLE"),
    .EXT_USR_FREQ_EN("DISABLE"),
    .FBCLK_DIV(1),
    .FBKCLK("CLKC0_EXT"),
    .FBKCLK_INT("VCO_PHASE0"),
    .FEEDBK_MODE("NORMAL"),
    .FIN("125.000"),
    .FRAC_ENABLE("DISABLE"),
    .FREQ_OFFSET(0),
    .GEN_BASIC_CLOCK("DISABLE"),
    .GMC_GAIN(3),
    .HIGH_SPEED_EN("DISABLE"),
    .ICP_CUR(13),
    .INTPI(0),
    .LPF_CAP(2),
    .LPF_RES(1),
    .MAIN_MUXC("MAIN"),
    .MPHASE_ENABLE("DISABLE"),
    .PD_DIG("DISABLE"),
    .PHASE_PATH_SEL(0),
    .PLL_FEED_TYPE("EXTERNAL"),
    .PLL_USR_RST("ENABLE"),
    .PREDIV_MUXC0("VCO"),
    .PREDIV_MUXC1("VCO"),
    .PREDIV_MUXC2("VCO"),
    .PREDIV_MUXC3("VCO"),
    .PREDIV_MUXC4("VCO"),
    .PREDIV_MUXC5("VCO"),
    .PREDIV_MUXC6("VCO"),
    .REFCLK_DET_BYP("DISABLE"),
    .REFCLK_DIV(1),
    .REFCLK_OUT_ENABLE("DISABLE"),
    .REFCLK_USR_RST("DISABLE"),
    .SDM_FRAC(0),
    .SSC_AMP(0.000000),
    .SSC_ENABLE("DISABLE"),
    .SSC_FREQ_DIV(0),
    .SSC_MODE("CENTER"),
    .SSC_RNGE(0),
    .WORK_MODE("USER"))
    pll_inst (
    .clkc_en(8'b00000011),
    .clkc_rst(2'b00),
    .cps_step(2'b00),
    .drp_addr(8'b00000000),
    .drp_clk(1'b0),
    .drp_rd(1'b0),
    .drp_rstn(1'b1),
    .drp_sel(1'b0),
    .drp_wdata(8'b00000000),
    .drp_wr(1'b0),
    .ext_freq_mod_clk(1'b0),
    .ext_freq_mod_en(1'b0),
    .ext_freq_mod_val(17'b00000000000000000),
    .fbclk(clk0_out),
    .pllpd(1'b0),
    .pllreset(reset),
    .psclk(1'b0),
    .psclksel(3'b000),
    .psdown(1'b0),
    .psstep(1'b0),
    .refclk(refclk),
    .refclk_rst(1'b0),
    .ssc_en(1'b0),
    .wakeup(1'b0),
    .clkc({open_n146,open_n147,open_n148,open_n149,open_n150,open_n151,clk1_out,clk0_buf}),
    .lock(lock));  // sys_pll.v(79)

endmodule 

