--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/2023/sgdma_prj_400k_20230831_ok (2)/sgdma_prj_400k_20230831_ok/sgdma_prj_400k_20230831/src/ram/dp_ram.vhd
 -- Date	:	2023 12 27
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY dp_ram IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	wea	: IN STD_LOGIC;
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(11 DOWNTO 0);
	ceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END dp_ram;

ARCHITECTURE struct OF dp_ram IS

	BEGIN
	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_A	=> 12,
			ADDR_WIDTH_B	=> 12,
			DATA_DEPTH_A	=> 4096,
			DATA_DEPTH_B	=> 4096,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			IMPLEMENT	=> "20K(FAST)",
			CLKMODE		=> "ASYNC",
			ECC_ENCODE		=> "DISABLE",
			ECC_DECODE		=> "DISABLE",
			SSROVERCE		=> "DISABLE",
			OREGSET_A		=> "SET",
			OREGSET_B		=> "SET",
			RESETMODE_A		=> "ASYNC",
			RESETMODE_B		=> "ASYNC",
			ASYNC_RESET_RELEASE_A		=> "SYNC",
			ASYNC_RESET_RELEASE_B		=> "SYNC",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> ceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> '0',
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			ecc_sbiterrinj	=> OPEN,
			ecc_dbiterrinj	=> OPEN,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
