/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/PCIE/scan/mjh_515/PCIE_ANLOGIC_SCAN_515/al_ip/fifo_generator_0.v
 ** Date	:	2024 05 11
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module fifo_generator_0 (
	rst,
	di, re, clk, we,
	dout,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [7:0] di;
	input clk, we;
	input re;

	output [7:0] dout;
	output empty_flag;
	output full_flag;
	output [13:0] rdusedw;
	output [13:0] wrusedw;

PH1_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(8),
	.ADDR_WIDTH(13),
	.SHOWAHEAD(0),
	.IMPLEMENT("20K")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clk(clk),
	.we(we),
	.dout(dout),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule