--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/PCIE/scan/mjh_515/PCIE_ANLOGIC_SCAN_515/al_ip/fifo_generator_0.vhd
 -- Date	:	2024 05 11
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY fifo_generator_0 IS
PORT (
	di	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	dout	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(13 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(13 DOWNTO 0)
	);
END fifo_generator_0;

ARCHITECTURE struct OF fifo_generator_0 IS

	BEGIN
	inst : PH1_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 8,
			ADDR_WIDTH			=> 13,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"20K"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			dout	=> dout,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
