--------------------------------------------------------------
 --  Copyright (c) 2012-2023 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/users/bswang/svn/sgdma128_mm/src/sgdma_app/ip/dram72x16.vhd
 -- Date	:	2023 02 22
 -- TD version	:	5.7.69285
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY dram72x16 IS
PORT (
	rdo	: OUT STD_LOGIC_VECTOR(71 DOWNTO 0);

	di	: IN STD_LOGIC_VECTOR(71 DOWNTO 0);
	waddr: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
	raddr	: IN STD_LOGIC_VECTOR(3 DOWNTO 0);
	we	: IN STD_LOGIC;
	wclk	: IN STD_LOGIC
	);
END dram72x16;

ARCHITECTURE struct OF dram72x16 IS

	BEGIN
	inst : PH1_LOGIC_DRAM
		GENERIC MAP (
			DATA_WIDTH_W	=> 72,
			ADDR_WIDTH_W	=> 4,
			DATA_DEPTH_W	=> 16,
			DATA_WIDTH_R	=> 72,
			ADDR_WIDTH_R	=> 4,
			DATA_DEPTH_R	=> 16,
			READREG			=> "DISABLE",
			FILL_ALL		=> "NONE",
			INIT_FILE		=> "NONE"
		)
		PORT MAP (
			di		=> di,
			waddr	=> waddr,
			we		=> we,
			wclk	=> wclk,
			rclk	=> '0',
			rrst	=> '0',
			rce		=> '0',
			rdoq	=> open,
			rdo		=> rdo,
			raddr	=> raddr
		);

END struct;
