/************************************************************\
 **  Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/users/bswang/svn/sgdma128_mm/src/sgdma_app/ip/dram72x16.v
 ** Date	:	2023 02 22
 ** TD version	:	5.7.69285
\************************************************************/

`timescale 1 ns / 1 ps

module dram72x16 ( di, waddr, we, wclk, rdo, raddr );

	parameter DATA_WIDTH_W = 72; 
	parameter ADDR_WIDTH_W = 4;
	parameter DATA_DEPTH_W = 16;
	parameter DATA_WIDTH_R = 72;
	parameter ADDR_WIDTH_R = 4;
	parameter DATA_DEPTH_R = 16;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] rdo;



	PH1_LOGIC_DRAM #(
 			.INIT_FILE("NONE"),
				.FILL_ALL("NONE"),
			.READREG("DISABLE"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.rclk(1'b0),
			.rrst(1'b0),
			.rce(1'b0),
			.rdoq(),
			.rdo(rdo),
			.raddr(raddr));

endmodule